apiVersion: v2
name: rag-aerospace
version: 0.1.0
appVersion: "1.0.0"
description: RAG API for aerospace docs
type: application
dependencies:
  - name: redis
    version: 18.17.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
