apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-backup-scripts
  namespace: rag-aerospace
data:
  backup.sh: |
    #!/bin/sh
    set -euo pipefail
    echo "starting milvus backup"
    date
    echo "milvus host: ${MILVUS_HOST:-} port: ${MILVUS_PORT:-}"
    echo "s3 bucket: ${S3_BUCKET:-} prefix: ${S3_PREFIX:-}"
    # placeholder for backup logic
    # integrate pymilvus export and upload to S3
    echo "backup completed"
  restore.sh: |
    #!/bin/sh
    set -euo pipefail
    echo "starting milvus restore validation"
    date
    echo "milvus host: ${MILVUS_HOST:-} port: ${MILVUS_PORT:-}"
    echo "s3 bucket: ${S3_BUCKET:-} prefix: ${S3_PREFIX:-}"
    # placeholder for restore validation logic
    echo "restore validation completed"
