apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-aerospace
spec:
  replicas: 2
  selector:
    matchLabels: { app: rag-aerospace }
  template:
    metadata:
      labels: { app: rag-aerospace }
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ name: http, containerPort: 8000 }]
          env:
{{- toYaml .Values.env | nindent 12 }}
{{- if .Values.redis.enabled }}
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379/0"
{{- end }}
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /ready, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
