name: ci
on:
  push: { branches: ["main"] }
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: pip install -r requirements.txt
      - run: pytest -q
  e2e:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: pip install -r requirements.txt
      - name: Start API (MOCK_MODE)
        env:
          METRICS_PUBLIC: "true"
          MOCK_MODE: "true"
          API_KEY: "TESTKEY"
          PORT: "8000"
        run: |
          nohup python -m uvicorn src.app.fastapi_app:app --host 127.0.0.1 --port 8000 &
          for i in {1..30}; do
            curl -sf http://127.0.0.1:8000/ready && break || sleep 1;
          done
          curl -sSf http://127.0.0.1:8000/metrics | head -n 5
      - name: Run smoke checks
        env:
          API_URL: "http://127.0.0.1:8000"
          API_KEY: "TESTKEY"
        run: |
          python scripts/smoke.py
      - name: Install k6
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gnupg2 ca-certificates
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update -y && sudo apt-get install -y k6
      - name: Run k6 smoke
        env:
          API_URL: "http://127.0.0.1:8000"
          API_KEY: "TESTKEY"
        run: |
          k6 run scripts/k6-smoke.js
  docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rag-aerospace:latest
