name: Eval Retrieval Quality
on:
  pull_request:
    paths:
      - 'src/app/**'
      - 'src/config.py'
      - 'src/index/**'
      - 'tests/eval/**'

jobs:
  eval:
    if: ${{ vars.EVAL_BASE_URL != '' }}
    runs-on: ubuntu-latest
    env:
      EVAL_BASE_URL: ${{ vars.EVAL_BASE_URL }}
      API_KEY: ${{ secrets.EVAL_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install eval dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Warmup check
        run: |
          set -e
          echo "Checking $EVAL_BASE_URL/health"
          curl -sf "$EVAL_BASE_URL/health" > /dev/null

      - name: Run eval
        run: |
          python tests/eval/run_eval.py | tee eval-result.json

      - name: Upload eval artifact
        uses: actions/upload-artifact@v4
        with:
          name: eval-result
          path: eval-result.json
